fgvc_aircraft:
  adam:
    lr: 1.0e-05
  rmsprop:
    lr: 1.0e-05
  sgd:
    lr: 0.5
  sgd_momentum:
    lr: 0.01
  signsgd:
    lr: 1.0e-05
  signsgd_momentum:
    lr: 1.0e-05
flowers102:
  adam:
    lr: 1.0e-05
  rmsprop:
    lr: 1.0e-05
  sgd:
    lr: 0.1
  sgd_momentum:
    lr: 0.01
  signsgd:
    lr: 0.0001
  signsgd_momentum:
    lr: 1.0e-05
